src/main/java/com/suntech/project/model/User.java
package com.suntech.project.model;

import lombok.Data;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

@Data
public class User implements Serializable {
    private Integer id;
    private String username;
    private String password;
    private Boolean isEnabled;
    private Date registerDate;
    private String name;
    private String surname;
    private String email;
    private String phone;

    public String getRegisterDateFmt(){
        return new SimpleDateFormat("dd/MM/yyyy").format(this.registerDate);
    }
}

src/main/java/com/suntech/project/controller/UserController.java
package com.suntech.project.controller;

import com.suntech.project.model.User;
import com.suntech.project.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;


@Controller
public class UserController {

    @Autowired
    private UserService userService;

//    @RequestMapping("/filter")
//    public List<User> filter(@RequestParam(value="user") User user){
//        return this.userService.findAllUsersBy(user);
//    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public ModelAndView getHome() {

        ModelAndView model = new ModelAndView("index", "user", new User());
        model.addObject("userList", this.userService.findAllUsers());

        return model;
    }

    @RequestMapping(value = "/filter", method = RequestMethod.POST)
    public ModelAndView doFilter(@ModelAttribute("user")User user) {

        ModelAndView model = new ModelAndView("index", "user", user);
        model.addObject("userList", this.userService.findAllUsersBy(user));

        return model;
    }

}

src/main/webapp/WEB-INF/jsp/index.jsp
<!doctype html>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Project Suntech</title>
</head>
<body>
    <div class="container">
        <h3>Users</h3>
        <h5>Filter</h5>
        <form:form method="POST" action="/filter" modelAttribute="user">
            <div class="form-row align-items-end">
                <div class="col-sm-3 my-1">
                    <label for="username">Username</label>
                    <form:input type="text" class="form-control mb-2" path="username" placeholder="Enter username"/>
                </div>
                <div class="col-sm-3 my-1">
                    <label for="name">Name</label>
                    <form:input type="text" class="form-control mb-2" path="name" placeholder="Enter name"/>
                </div>
                <div class="col-sm-3 my-1">
                    <label for="email">Email</label>
                    <form:input type="email" class="form-control mb-2" path="email" placeholder="Enter email"/>
                </div>
                <div class="col-sm-3 my-1">
                    <button type="submit" class="btn btn-primary mb-2">Filter</button>
                </div>
            </div>
        </form:form>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Username</th>
                    <th scope="col">Password</th>
                    <th scope="col">Enabled</th>
                    <th scope="col">Registration Date</th>
                    <th scope="col">Name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone</th>
                </tr>
                </thead>
                <tbody>
                <c:forEach var="user" items="${userList}">
                    <tr>
                        <th scope="row">${user.id}</th>
                        <td>${user.username}</td>
                        <td>${user.password}</td>
                        <td>${user.isEnabled}</td>
                        <td>${user.registerDateFmt}</td>
                        <td>${user.name}</td>
                        <td>${user.surname}</td>
                        <td>${user.email}</td>
                        <td>${user.phone}</td>
                    </tr>
                </c:forEach>
                </tbody>
            </table>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>